### ISSUE TITLE
Migrate to PostgreSQL

### ISSUE THREAD

**Issue by oldcryptogeek** [Kodex-Data-Systems/Casper#1]
Currently the database is not encrypted and introduces security vulnerabilities.  Although there are options for encrypting sqlite databases, I'd like to migrate to PostgreSQL at this time.

https://stackoverflow.com/questions/5669905/sqlite-with-encryption-password-protection

https://www.postgresql.org/docs/8.1/encryption-options.html

**Comment by WizardsOrb** [comment]
Usual async en/decryption of stored values will be enough.
