### ISSUE TITLE
Empty leaderlogs fatal error

### ISSUE THREAD

**Issue by dmitrystas** [Kodex-Data-Systems/Casper#15]
log
> Traceback (most recent call last):
>   File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "./__main__.py", line 305, in <module>
>     cliui.run()
>   File "./__main__.py", line 238, in run
>     header = leaderlogs[0].keys()
> IndexError: list index out of range

need to check leaderlogs, something like this

```
            if choice == '14': #  Show Leaders Logs.
                self.clear()
                #  pprint.pprint(casper.node.show_leader_logs())
                leaderlogs = casper.node.show_leader_logs()
                if leaderlogs:
                    header = leaderlogs[0].keys()
                    rows =  [x.values() for x in leaderlogs]
                    table = tabulate(rows, header, tablefmt="psql")
                    print(table)
                else:
                    print('The leaderlogs are empty')
```

**Comment by WizardsOrb** [comment]
thx
