### ISSUE TITLE
Running python3 config fails as _path is not set correctly

### ISSUE THREAD

**Issue by Scitz0** [Kodex-Data-Systems/Casper#23]
Ran as instruction say "python3 config" to start configuration of Casper from root dir of Casper.
It failed with below error message.
————————
File "config/__main__.py", line 85, in _load_sql
    with open (_path, "r") as file:
UnboundLocalError: local variable '_path' referenced before assignment
————————
Seems like os.path.dirname(file) doesn't return either "." or "./config" so _path variable is not set and open function fails.
Running just "python3 ." and let it force a config on first run solved my issue.

**Comment by WizardsOrb** [comment]
thx, fixed, please verify. if still buggy, reopen issue please
