### ISSUE TITLE
Create Stake Pool adding newline character in node secret yaml file

### ISSUE THREAD

**Issue by Scitz0** [Kodex-Data-Systems/Casper#25]
I noticed that the 'Create Stake Pool' function adds a newline "\n" character in node secret yaml file at the end of the node_id line inside the quotation. 

node_id: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\n"

**Comment by WizardsOrb** [comment]
thx!
