### ISSUE TITLE
Delegate to Stake Pool in MacOs

### ISSUE THREAD

**Issue by benjehan** [Kodex-Data-Systems/Casper#7]
error: Invalid value for '<STAKE_KEY>': Failed to parse bech32, invalid data format

Certificate Fee: 100 
Coefficient: 5 
Fee Constant: 10 
Total: 115
error: The following required arguments were not provided:
    <value>

USAGE:
    jcli transaction add-certificate <value> --staging <staging-file>

For more information try --help
could not process secret file 'could not decode secret file 'witness.secret.tmp': Failed to parse bech32, invalid data format'
  |-> could not decode secret file 'witness.secret.tmp': Failed to parse bech32, invalid data format
  |-> Failed to parse bech32, invalid data format
  |-> missing human-readable separator, "1"
could not parse Bech32 in witness file 'witness.output.tmp'
  |-> invalid length
invalid number of witnesses in transaction to seal: 0, should be 1
certificate error invalid input file path 'stake_key.sk'
cannot get message from transaction in finalizing state
input is not a valid fragment
  |-> failed to fill whole buffer
Traceback (most recent call last):
  File "caspercli.py", line 268, in <module>
    cliui.run()
  File "caspercli.py", line 128, in run
    casper.cli.create_delegation_certificate(pool, public, secret, account)
  File "/Users/Ben/Casper/casper/cli.py", line 245, in create_delegation_certificate
    self._send_certificate(account, sk)
  File "/Users/Ben/Casper/casper/cli.py", line 304, in _send_certificate
    shell=True
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'jcli transaction to-message --staging file.staging | jcli rest v0 message post -h http://localhost:3101/api' returned non-zero exit status 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by oldcryptogeek** [comment]
@benjehan https://github.com/Kodex-Data-Systems/Casper/tree/v0.0.3

**Comment by oldcryptogeek** [comment]
Fixed by v0.0.3

https://github.com/Kodex-Data-Systems/Casper/pull/10
